/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by terrajet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type QuotasetV2Observation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type QuotasetV2Parameters struct {

	// +kubebuilder:validation:Optional
	Cores *float64 `json:"cores,omitempty" tf:"cores,omitempty"`

	// +kubebuilder:validation:Optional
	FixedIps *float64 `json:"fixedIps,omitempty" tf:"fixed_ips,omitempty"`

	// +kubebuilder:validation:Optional
	FloatingIps *float64 `json:"floatingIps,omitempty" tf:"floating_ips,omitempty"`

	// +kubebuilder:validation:Optional
	InjectedFileContentBytes *float64 `json:"injectedFileContentBytes,omitempty" tf:"injected_file_content_bytes,omitempty"`

	// +kubebuilder:validation:Optional
	InjectedFilePathBytes *float64 `json:"injectedFilePathBytes,omitempty" tf:"injected_file_path_bytes,omitempty"`

	// +kubebuilder:validation:Optional
	InjectedFiles *float64 `json:"injectedFiles,omitempty" tf:"injected_files,omitempty"`

	// +kubebuilder:validation:Optional
	Instances *float64 `json:"instances,omitempty" tf:"instances,omitempty"`

	// +kubebuilder:validation:Optional
	KeyPairs *float64 `json:"keyPairs,omitempty" tf:"key_pairs,omitempty"`

	// +kubebuilder:validation:Optional
	MetadataItems *float64 `json:"metadataItems,omitempty" tf:"metadata_items,omitempty"`

	// +kubebuilder:validation:Required
	ProjectID *string `json:"projectId" tf:"project_id,omitempty"`

	// +kubebuilder:validation:Optional
	RAM *float64 `json:"ram,omitempty" tf:"ram,omitempty"`

	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// +kubebuilder:validation:Optional
	SecurityGroupRules *float64 `json:"securityGroupRules,omitempty" tf:"security_group_rules,omitempty"`

	// +kubebuilder:validation:Optional
	SecurityGroups *float64 `json:"securityGroups,omitempty" tf:"security_groups,omitempty"`

	// +kubebuilder:validation:Optional
	ServerGroupMembers *float64 `json:"serverGroupMembers,omitempty" tf:"server_group_members,omitempty"`

	// +kubebuilder:validation:Optional
	ServerGroups *float64 `json:"serverGroups,omitempty" tf:"server_groups,omitempty"`
}

// QuotasetV2Spec defines the desired state of QuotasetV2
type QuotasetV2Spec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     QuotasetV2Parameters `json:"forProvider"`
}

// QuotasetV2Status defines the observed state of QuotasetV2.
type QuotasetV2Status struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        QuotasetV2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// QuotasetV2 is the Schema for the QuotasetV2s API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,openstackjet}
type QuotasetV2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              QuotasetV2Spec   `json:"spec"`
	Status            QuotasetV2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// QuotasetV2List contains a list of QuotasetV2s
type QuotasetV2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []QuotasetV2 `json:"items"`
}

// Repository type metadata.
var (
	QuotasetV2_Kind             = "QuotasetV2"
	QuotasetV2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: QuotasetV2_Kind}.String()
	QuotasetV2_KindAPIVersion   = QuotasetV2_Kind + "." + CRDGroupVersion.String()
	QuotasetV2_GroupVersionKind = CRDGroupVersion.WithKind(QuotasetV2_Kind)
)

func init() {
	SchemeBuilder.Register(&QuotasetV2{}, &QuotasetV2List{})
}
