/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by terrajet. DO NOT EDIT.

// Package apis contains Kubernetes API for the provider.
package apis

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/juliosueiras/provider-jet-openstack/apis/blockstorage/v1alpha1"
	v1alpha1compute "github.com/juliosueiras/provider-jet-openstack/apis/compute/v1alpha1"
	v1alpha1containerinfra "github.com/juliosueiras/provider-jet-openstack/apis/containerinfra/v1alpha1"
	v1alpha1db "github.com/juliosueiras/provider-jet-openstack/apis/db/v1alpha1"
	v1alpha1dns "github.com/juliosueiras/provider-jet-openstack/apis/dns/v1alpha1"
	v1alpha1fw "github.com/juliosueiras/provider-jet-openstack/apis/fw/v1alpha1"
	v1alpha1identity "github.com/juliosueiras/provider-jet-openstack/apis/identity/v1alpha1"
	v1alpha1images "github.com/juliosueiras/provider-jet-openstack/apis/images/v1alpha1"
	v1alpha1keymanager "github.com/juliosueiras/provider-jet-openstack/apis/keymanager/v1alpha1"
	v1alpha1lb "github.com/juliosueiras/provider-jet-openstack/apis/lb/v1alpha1"
	v1alpha1networking "github.com/juliosueiras/provider-jet-openstack/apis/networking/v1alpha1"
	v1alpha1objectstorage "github.com/juliosueiras/provider-jet-openstack/apis/objectstorage/v1alpha1"
	v1alpha1orchestration "github.com/juliosueiras/provider-jet-openstack/apis/orchestration/v1alpha1"
	v1alpha1sharedfilesystem "github.com/juliosueiras/provider-jet-openstack/apis/sharedfilesystem/v1alpha1"
	v1alpha1apis "github.com/juliosueiras/provider-jet-openstack/apis/v1alpha1"
	v1alpha1vpnaas "github.com/juliosueiras/provider-jet-openstack/apis/vpnaas/v1alpha1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1compute.SchemeBuilder.AddToScheme,
		v1alpha1containerinfra.SchemeBuilder.AddToScheme,
		v1alpha1db.SchemeBuilder.AddToScheme,
		v1alpha1dns.SchemeBuilder.AddToScheme,
		v1alpha1fw.SchemeBuilder.AddToScheme,
		v1alpha1identity.SchemeBuilder.AddToScheme,
		v1alpha1images.SchemeBuilder.AddToScheme,
		v1alpha1keymanager.SchemeBuilder.AddToScheme,
		v1alpha1lb.SchemeBuilder.AddToScheme,
		v1alpha1networking.SchemeBuilder.AddToScheme,
		v1alpha1objectstorage.SchemeBuilder.AddToScheme,
		v1alpha1orchestration.SchemeBuilder.AddToScheme,
		v1alpha1sharedfilesystem.SchemeBuilder.AddToScheme,
		v1alpha1apis.SchemeBuilder.AddToScheme,
		v1alpha1vpnaas.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
